model_name: "Llama 3.1 405B Instruct VLLM"
python_version: py311
model_metadata:
  example_model_input: {"prompt": "what is the meaning of life"}
  repo_id: meta-llama/Meta-Llama-3.1-405B-Instruct-FP8
  tensor_parallel: 8
requirements:
  - vllm==0.6.0
  - transformers==4.43.2
resources:
  accelerator: H100:8
  use_gpu: true
runtime:
  predict_concurrency: 128
secrets:
  hf_access_token: null
