description: "LLaVA v1.6 34B for vision-language tasks"
environment_variables: {}
external_package_dirs: []
model_name: llava-v1.6-34b
python_version: py311
requirements:
- git+https://github.com/haotian-liu/LLaVA.git
model_metadata:
  repo_id: "liuhaotian/llava-v1.6-34b"
  example_model_input: {"query": "Describe this image in detail", "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Cat03.jpg/1200px-Cat03.jpg"}
resources:
  accelerator: A100
  use_gpu: true
secrets: {}
system_packages: []
