description: Generate text with an instruction-tuned version of Mistral 7B.
model_metadata:
  avatar_url: https://cdn.baseten.co/production/static/explore/mistral_logo.png
  cover_image_url: https://cdn.baseten.co/production/static/explore/mistral.png
  engine_args:
    model: mistralai/Mistral-7B-Instruct-v0.1
    enable_lora: true
    max_loras: 256
    max_lora_rank: 32
    max_cpu_loras: 500
  example_model_input:
    prompt: What is the Mistral wind?
    lora_model: OpenPipe/sample-lora-pii-redaction
  pretty_name: Mistral 7B LORA
  prompt_format: <s>[INST] {prompt} [/INST]
  tags:
  - text-generation
model_name: Mistral 7B vLLM Lora
python_version: py311
requirements: 
- vllm==0.3.1
resources:
  accelerator: A100
  memory: 25Gi
runtime:
  predict_concurrency: 256
