description: "black-forest-labs/FLUX.1-dev for image generation"
external_package_dirs: []
model_metadata:
  example_model_input: {"prompt": 'black forest gateau cake spelling out the words "FLUX DEV", tasty, food photography, dynamic shot'}
  repo_id: black-forest-labs/FLUX.1-dev
model_name: Flux.1-dev
python_version: py311
requirements:
  - git+https://github.com/huggingface/diffusers.git@fc6a91e3834c35e57b398ad1c0d99f6f83557e04
  - transformers==4.36.0
  - accelerate==0.25.0
  - sentencepiece==0.1.99
  - protobuf==4.25.1
resources:
  accelerator: H100_40GB
  use_gpu: true
secrets:
  hf_access_token: null
system_packages:
  - ffmpeg
  - libsm6
  - libxext6
