base_image:
  image: nvcr.io/nvidia/tritonserver:23.10-trtllm-python-py3
  python_executable_path: /usr/bin/python3
environment_variables: {}
external_package_dirs: []
model_metadata:
  example_model_input: {"text_input": "What's the meaning of life?"}
  avatar_url: https://cdn.baseten.co/production/static/explore/meta.png
  cover_image_url: https://cdn.baseten.co/production/static/explore/llama.png
  tags:
  - text-generation
  tensor_parallelism: 1
  engine_repository: "baseten/llama_7b_sq0.8_bs_64_kv_2000"
  tokenizer_repository: "NousResearch/Llama-2-7b-chat-hf"
description: Generate text from a prompt with this seven billion parameter language model.
model_name: Llama 7B Chat TRT
python_version: py311
requirements:
- tritonclient[all]
resources:
  accelerator: A100
  use_gpu: true
secrets: {}
system_packages: []
runtime:
  predict_concurrency: 256
