description: "XTTS V2 for text-to-speech"
environment_variables:
  COQUI_TOS_AGREED: "1"
external_package_dirs: []
model_metadata:
  repo_id: "coqui/XTTS-v2"
  example_model_input:
    language: en
    speaker_voice: Claribel Dervla
    text: Kurt watched the incoming Pelicans. The blocky jet-powered craft were so distant they were only specks against the setting sun. He hit the magnification on his faceplate and saw lines of fire tracing their reentry vectors. They would touch down in three minutes.
  tags:
  - text-to-speech
model_name: XTTS V2
python_version: py310
requirements:
  - git+https://github.com/htrivedi99/TTS.git
resources:
  accelerator: T4
  cpu: '3'
  memory: 10Gi
  use_gpu: true
secrets: {}
system_packages: []
