environment_variables: {}
external_package_dirs: []
model_name: Mixtral 8x7B — VLLM TP2 — A100
python_version: py310
requirements:
- vllm
resources:
  accelerator: A100:2
  use_gpu: true
runtime:
  predict_concurrency: 128
secrets: {}
system_packages: []
