model_metadata:
  example_model_input:
    model: "EssentialAI/rnj-1-instruct"
    messages:
      - role: system
        content: "You are a helpful AI assistant."
      - role: user
        content: "Who are you?"
    max_tokens: 4096
    temperature: 0.2
  tags:
    - openai-compatible
model_name: rnj-1-instruct
base_image:
  image: vllm/vllm-openai:v0.12.0
docker_server:
  start_command:  vllm serve EssentialAI/rnj-1-instruct --enable-auto-tool-choice --tool-call-parser hermes  --host 0.0.0.0 --port 8000 --trust-remote-code
  readiness_endpoint: /health
  liveness_endpoint: /health
  predict_endpoint: /v1/chat/completions
  server_port: 8000
resources:
  accelerator: H100
  use_gpu: true
runtime:
  predict_concurrency: 256
