base_image:
  image: baseten/truss-server-base:3.10-gpu-v0.4.9
  python_executable_path: /usr/bin/python3
environment_variables: {}
external_package_dirs: []
model_metadata:
  whisper_model: medium
model_name: Whisper Streaming
python_version: py310
requirements: []
requirements_file: ./requirements.txt
resources:
  accelerator: T4
  use_gpu: true
secrets: {}
system_packages:
- ffmpeg
