base_image:
  image: nvcr.io/nvidia/pytorch:25.06-py3
description: Generate high-quality images from text prompts using Black Forest Labs's Flux model with TensorRT optimization.
external_package_dirs: []
model_metadata:
  repo_id: "black-forest-labs/FLUX.1-dev"
  example_model_input:
    prompt: A photo of an astronaut riding a horse
model_name: Flux 1.0 Dev - TensorRT
requirements_file: ./requirements.txt
resources:
  accelerator: B200
  use_gpu: true
runtime:
  predict_concurrency: 1
secrets:
  hf_access_token: null
system_packages:
- ffmpeg
- libsm6
- libxext6
