base_image: null
bundled_packages_dir: packages
data_dir: data
description: null
environment_variables: {}
examples_filename: examples.yaml
external_package_dirs: []
input_type: Any
live_reload: false
model_class_filename: model.py
model_class_name: Model
model_framework: custom
model_metadata: {}
model_module_dir: model
model_name: Falcon 7B
model_type: custom
python_version: py39
requirements:
- torch
- peft
- sentencepiece
- accelerate
- bitsandbytes
- einops
- git+https://github.com/huggingface/transformers.git
- safetensors
- scipy
- protobuf==3.20.*
resources:
  cpu: "3"
  memory: 14Gi
  use_gpu: true
  accelerator: A100:1
secrets: {}
spec_version: '2.0'
system_packages: []