description: "ZenCtrl for image generation"
base_image:
  image: fotographerai/zenctrlstage:latest
model_metadata:
  repo_id: "Kijai/ZenCtrl-Flux-comfy"
  example_model_input:
    image: "<base64-encoded image>"
    prompt: A man holding a camera facing the objective
    steps: 10
docker_server:
  start_command: sh -c "HF_TOKEN=$(cat /secrets/hf_access_token) python -m uvicorn app:app --host 0.0.0.0 --port 8000 --log-level debug"
  readiness_endpoint: /health
  liveness_endpoint: /health
  predict_endpoint: /generate
  server_port: 8000
resources:
  accelerator: H100
  use_gpu: true
model_name: ZenCtrl
environment_variables:
  PORT: 8000
  HF_TOKEN: null
runtime:
  predict_concurrency: 8
secrets:
  hf_access_token: null
