build_commands: []
environment_variables: {}
external_package_dirs: []
model_metadata:
  tags:
    - openai-compatible
  example_model_input:
    {
      messages:
        [
          {
            role: "system",
            content: "You are a knowledgable, engaging, meteorology teacher.",
          },
          {
            role: "user",
            content: "What is the impact of the Mistral wind on the French climate?",
          },
        ],
      stream: true,
      max_tokens: 512,
      temperature: 0.9,
    }
  repo_id: mistralai/Mixtral-8x7B-Instruct-v0.1
model_name: Mistral 8x7B Instruct
python_version: py39
requirements: []
resources:
  accelerator: H100
  cpu: "1"
  memory: 24Gi
  use_gpu: true
secrets:
  hf_access_token: set token in baseten workspace
system_packages: []
trt_llm:
  build:
    base_model: decoder
    checkpoint_repository:
      repo: mistralai/Mixtral-8x7B-Instruct-v0.1
      source: HF
    num_builder_gpus: 2
    quantization_type: fp8_kv
    max_seq_len: 32768
    tensor_parallel_count: 1
    plugin_configuration:
      use_paged_context_fmha: true
      use_fp8_context_fmha: true
      paged_kv_cache: true
  runtime:
    batch_scheduler_policy: max_utilization
    enable_chunked_context: true
    request_default_max_tokens: 32768
