environment_variables: {}
external_package_dirs: []
model_metadata: {}
model_name: Llama 3.1 70B vLLM
python_version: py310
requirements:
  - vllm==0.5.3post1
  - accelerate
resources:
  accelerator: H100:4
  use_gpu: true
runtime:
  predict_concurrency: 128
secrets:
  hf_access_token: ""
system_packages:
  - python3.10-venv
