build_commands: []
environment_variables: {}
external_package_dirs: []
model_metadata:
  example_model_input:
    inputs:
    - - Baseten is a fast inference provider
    - - Classify this separately.
    raw_scores: true
    truncate: true
    truncation_direction: Right
model_name: BEI-allenai-llama-3.1-tulu-3-8b-reward-model-fp8-truss-example
python_version: py39
requirements: []
resources:
  accelerator: H100_40GB
  cpu: '1'
  memory: 10Gi
  use_gpu: true
secrets: {}
system_packages: []
trt_llm:
  build:
    base_model: encoder
    checkpoint_repository:
      repo: allenai/Llama-3.1-Tulu-3-8B-RM
      revision: main
      source: HF
    max_num_tokens: 131072
    num_builder_gpus: 1
    quantization_type: fp8
  runtime:
    webserver_default_route: /predict
