base_image:
  image: nvcr.io/nvidia/pytorch:23.11-py3
  python_executable_path: /usr/bin/python
description: Generate original images from text prompts.
environment_variables:
  HF_HUB_ENABLE_HF_TRANSFER: 1
external_package_dirs: []
model_cache:
- repo_id: baseten/sdxl-1.0-trt-8.6.1.post1-engine
  use_volume: false
- allow_patterns:
  - config.json
  - diffusion_pytorch_model.safetensors
  repo_id: madebyollin/sdxl-vae-fp16-fix
  use_volume: false
- allow_patterns:
  - '*.json'
  - '*.fp16.safetensors'
  - sd_xl_base_1.0.safetensors
  repo_id: stabilityai/stable-diffusion-xl-base-1.0
  use_volume: false
- allow_patterns:
  - '*.json'
  - '*.fp16.safetensors'
  - sd_xl_refiner_1.0.safetensors
  repo_id: stabilityai/stable-diffusion-xl-refiner-1.0
  use_volume: false
model_metadata:
  avatar_url: https://cdn.baseten.co/production/static/stability.png
  cover_image_url: https://cdn.baseten.co/production/static/sd.png
  example_model_input:
    prompt: Astronaut in a jungle, cold color palette, muted colors, detailed, 8k
  pretty_name: Stable Diffusion XL - TensorRT
  tags:
  - image-generation
model_name: Stable Diffusion XL - TensorRT
python_version: py39
requirements:
- accelerate==0.25.0
- colored==2.2.4
- cuda-python==12.3.0
- ftfy==6.1.3
- nvtx==0.2.10
- opencv-python==4.8.0.74
- scipy==1.11.4
- transformers==4.31.0
- safetensors==0.4.1
- hf_transfer==0.1.4
- diffusers==0.23.1
- invisible-watermark>=0.2.0
- --extra-index-url https://pypi.ngc.nvidia.com
- polygraphy==0.49.9
- --extra-index-url https://pypi.nvidia.com
- tensorrt==8.6.1.post1
resources:
  accelerator: A100
  use_gpu: true
runtime:
  predict_concurrency: 1
secrets: {}
system_packages:
- python3.10-venv
- ffmpeg
- libsm6
- libxext6
