description: "Sana 1600M for image generation"
build_commands: []
base_image:
  image: alphatozeta/cuda-python:12.1.1-cudnn8-devel-ubuntu22.04
environment_variables: {}
external_package_dirs: []
model_metadata:
  repo_id: "Efficient-Large-Model/Sana_1600M_1024px_MultiLing_diffusers"
  example_model_input: {
    "prompt": "a photo of an astronaut riding a horse on mars",
    "height": 1024,
    "width": 1024,
    "guidance_scale": 5.0,
    "pag_guidance_scale": 2.0,
    "num_inference_steps": 18,
    "seed": 4096,
  }
model_name: Sana 1600M
python_version: py311
requirements:
- git+https://github.com/NVlabs/Sana.git@d7945026d8d85008aca1d1e6db5717a1069f5c84
- huggingface-hub==0.26.3
- hf-transfer==0.1.8
resources:
  accelerator: H100_40GB
  use_gpu: true
secrets:
  hf_access_token: "null"
system_packages:
- ffmpeg
- libsm6
- libxext6
- python3.10-venv
