description: NSQL is an open-source text-to-SQL AI model developed by Numbers Station.
environment_variables: {}
external_package_dirs: []
model_metadata:
  repo_id: "NumbersStation/nsql-350M"
  avatar_url: https://aeiljuispo.cloudimg.io/v7/https://cdn-uploads.huggingface.co/production/uploads/649c7ee8f97bd6fd710a9eb5/nBg1Fyo22RrqRJrkz9IYB.png
  cover_image_url: https://global-uploads.webflow.com/6348b2d49808811e3f7a0fff/640690727b722a05771960ec_graphic-data-p-800.png
  tags:
  - code-generation
  example_model_input: {"schema": "CREATE TABLE stadium (stadium_id number, location text, name text, capacity number)", "query": "What is the total capacity of all stadiums?"}
model_name: NSQL 350M
python_version: py39
requirements:
- torch==2.1.0
- transformers>=4.29.0
resources:
  accelerator: A10G
  cpu: '8'
  memory: 30Gi
  use_gpu: true
secrets: {}
system_packages: []
