description: MusicGen Melody is a simple and controllable model for music generation
  conditioned on text and audio. It is developed by Facebook AI Research.
environment_variables: {}
external_package_dirs: []
model_metadata:
  repo_id: "facebook/musicgen-melody"
  avatar_url: https://cdn.baseten.co/production/static/explore/meta.png
  cover_image_url: https://cdn.baseten.co/production/static/explore/musicgen-cover.png
  example_model_input:
    duration: 8
    prompts:
    - happy rock
    - energetic EDM
    - sad jazz
  tags:
  - text-to-music
model_name: MusicGen Melody
python_version: py39
requirements:
- torch>=2
- audiocraft==1.3.0
- protobuf==4.25.1
resources:
  accelerator: A10G
  cpu: '3'
  memory: 14Gi
  use_gpu: true
secrets: {}
system_packages:
- ffmpeg
