environment_variables: {}
external_package_dirs: []
model_name: Vicunlocked-Alpaca-30B
python_version: py39
requirements:
- torch
- peft
- sentencepiece
- accelerate
- bitsandbytes
- einops
- git+https://github.com/huggingface/transformers.git
resources:
  accelerator: A100:1
  cpu: '3'
  memory: 50Gi
  use_gpu: true
secrets: {}
system_packages: []
