environment_variables: {}
external_package_dirs: []
model_metadata: {}
model_name: mistral-7b
python_version: py311
requirements:
- transformers==4.34.0
- sentencepiece
- accelerate
- torch==2.0.1
resources:
  accelerator: A10G
  use_gpu: true
  memory: 25Gi
secrets: {}
system_packages: []
