model_metadata:
  example_model_input:
    encoding_format: float
    input: text string
    model: model
model_name: nginx_test
python_version: py39
resources:
  accelerator: L4
  cpu: '1'
  memory: 10Gi
  use_gpu: true
trt_llm:
  build:
    base_model: encoder
    checkpoint_repository:
      repo: michaelfeil/Qwen3-Embedding-0.6B-auto
      revision: main
      source: HF
    max_num_tokens: 32768
    num_builder_gpus: 4
    quantization_type: fp8
  runtime:
    webserver_default_route: /v1/embeddings
