base_image:
  image: docker.io/baseten/trtllm-server:r23.12_baseten_v0.7.1
  python_executable_path: /usr/bin/python3
description: Generate text from a prompt with this seven billion parameter language
  model.
environment_variables:
  HF_HUB_ENABLE_HF_TRANSFER: true
external_package_dirs: []
model_metadata:
  avatar_url: https://cdn.baseten.co/production/static/explore/meta.png
  cover_image_url: https://cdn.baseten.co/production/static/explore/llama.png
  engine_repository: baseten/Gryphe_MythoMax-L2-13b_v0.7.1_H100-80GB-HBM3_2ff724
  example_model_input:
    max_tokens: 1024
    prompt: What's the meaning of life?
  repo_id: NousResearch/Llama-2-13b-chat-hf
  tags:
  - text-generation
  tensor_parallelism: 1
  tokenizer_repository: NousResearch/Llama-2-7b-chat-hf
model_name: Mythomax 13b
python_version: py311
requirements:
- tritonclient[all]
- hf_transfer
resources:
  accelerator: H100
  use_gpu: true
runtime:
  predict_concurrency: 256
secrets: {}
system_packages: []
