bundled_packages_dir: packages
data_dir: data
description: Generate text from a prompt with this seven billion parameter language model.
environment_variables: {}
examples_filename: examples.yaml
external_package_dirs: []
input_type: Any
live_reload: false
model_class_filename: model.py
model_class_name: Model
model_framework: custom
model_metadata:
  example_model_input: {"prompt": "What's the meaning of life?", "temperature": 0.1, "top_p": 0.75,"num_beams": 4}
  avatar_url: https://cdn.baseten.co/production/static/explore/meta.png
  cover_image_url: https://cdn.baseten.co/production/static/explore/llama.png
  tags:
  - text-generation
model_module_dir: model
model_name: Llama-2-chat 7B
model_type: custom
python_version: py38
requirements:
- torch
- peft
- sentencepiece
- accelerate
- bitsandbytes
- einops
- git+https://github.com/huggingface/transformers.git
- faker
- math0
- safetensors
- scipy
- protobuf==3.20.*
resources:
  cpu: "3"
  memory: 14Gi
  use_gpu: true
  accelerator: A10G
secrets:
  hf_access_token: "ENTER HF ACCESS TOKEN HERE"
spec_version: '2.0'
system_packages: []