environment_variables: {}
external_package_dirs: []
model_metadata:
  example_model_input:
    prompt: What happens if I go to the top of the tallest mountian in california
      with a bucket of water and tip it over the highest cliff?
model_name: Nous Capybara 34B
python_version: py310
requirements:
- accelerate==0.25.0
- transformers==4.35.2
- torch==2.1.0
- bitsandbytes==0.41.3
- scipy==1.11.4
- sentencepiece==0.1.99
resources:
  accelerator: A100
  cpu: '3'
  memory: 20Gi
  use_gpu: true
secrets: {}
system_packages: []
