description: "N-gram speculative decoding example via Truss"
build_commands: []
environment_variables: {}
external_package_dirs: []
model_metadata:
  repo_id: "NousResearch/Meta-Llama-3.1-8B-Instruct"
  example_model_input: {"messages": [{"role": "user", "content": "What is machine learning?"}], "max_tokens": 512}
model_name: ngram-speculator
python_version: py310
requirements:
- vllm==0.6.5
- transformers==4.47.1
resources:
  accelerator: H100
  use_gpu: True
secrets: {}
system_packages: []
