build_commands: []
base_image:
  image: alphatozeta/cuda-python:12.1.1-cudnn8-devel-ubuntu22.04
  python_executable_path: /usr/bin/python3
model_name: segment-anything-2
environment_variables: {}
external_package_dirs: []
model_metadata:
  example_model_input: {"image": "what is the meaning of life", "points_per_side": 32, "pred_iou_thresh": 0.8, "stability_score_thresh": 0.95, "use_m2m": true}
python_version: py310
requirements:
  - torch==2.4.0
  - torchvision==0.19.0
  - numpy==1.26.4
  - tqdm==4.66.5
  - hydra-core==1.3.2
  - httpx==0.27.0
  - iopath==0.1.10
  - pillow==10.4.0
  - matplotlib==3.9.1
  - jupyter==1.0.0
  - opencv-python-headless==4.8.0.74
  - black==24.8.0
  - usort==1.0.8.post1
  - ufmt==2.7.0
resources:
  accelerator: A10G
  use_gpu: true
secrets: {}
system_packages:
  - libgl1-mesa-glx
  - libglib2.0-0
  - ninja-build
  - python3.10-venv
