description: "mistral-7b for text generation"
environment_variables: {}
external_package_dirs: []
model_metadata:
  repo_id: "mistralai/Mistral-7B-v0.1"
  avatar_url: https://cdn.baseten.co/production/static/explore/mistral_logo.png
  cover_image_url: https://cdn.baseten.co/production/static/explore/mistral.png
  example_model_input:
    prompt: What is the Mistral wind?
  pretty_name: Mistral 7B
  tags:
  - text-generation
model_name: mistral-7b
python_version: py311
requirements:
- transformers==4.42.3
- sentencepiece==0.1.99
- accelerate==0.25.0
- torch==2.0.1
- numpy==1.26.4
resources:
  accelerator: A10G
  memory: 25Gi
  use_gpu: true
secrets:
  hf_access_token: "ENTER HF ACCESS TOKEN HERE"
system_packages: []
