description: Parakeet TDT 0.6B V3 is a 600-million-parameter automatic speech recognition (ASR) model designed for high-quality multi-language transcription.
python_version: py312
model_metadata:
  repo_id: nvidia/parakeet-tdt-0.6b-v3
  avatar_url: https://cdn-avatars.huggingface.co/v1/production/uploads/1613114437487-60262a8e0703121c822a80b6.png
  example_model_input:
    {
      "audio_url": "https://dldata-public.s3.us-east-2.amazonaws.com/2086-149220-0033.wav",
      "timestamps": false
    }
system_packages:
  - ffmpeg
resources:
  accelerator: H100_40GB
  use_gpu: true
runtime:
  predict_concurrency: 8
model_name: Parakeet TDT 0.6B V3
secrets:
  hf_access_token: null
model_cache:
  - repo_id: nvidia/parakeet-tdt-0.6b-v3
    revision: main
    use_volume: true
    volume_folder: parakeet-tdt-0.6b-v3
    runtime_secret_name: hf_access_token
    kind: hf
requirements:
  - nemo_toolkit[asr]
  - requests
  - pyarrow==20.0.0
  - cuda-python>=12.3