environment_variables: {}
external_package_dirs: []
model_metadata:
  avatar_url: https://cdn.baseten.co/production/static/explore/meta.png
  cover_image_url: https://cdn.baseten.co/production/static/explore/llama.png
  repo_id: meta-llama/Meta-Llama-3-8B-Instruct
  tags:
  - text-generation
model_name: Llama 3 8B Instruct
python_version: py310
model_cache:
  - repo_id: meta-llama/Meta-Llama-3-8B-Instruct
requirements:
  - accelerate
  - einops
  - transformers
  - torch
resources:
  accelerator: H100
  use_gpu: true
secrets:
  hf_access_token: "your-hf-access-token"
system_packages: []
