build_commands: []
environment_variables: {}
external_package_dirs: []
model_metadata:
  example_model_input:
    inputs: Baseten is a fast inference provider
    raw_scores: true
    truncate: true
    truncation_direction: Right
model_name: BEI-skywork-skywork-reward-llama-3.1-8b-v0.2-reward-model-fp8-truss-example
python_version: py39
requirements: []
resources:
  accelerator: H100_40GB
  cpu: '1'
  memory: 10Gi
  use_gpu: true
secrets: {}
system_packages: []
trt_llm:
  build:
    base_model: encoder
    checkpoint_repository:
      repo: Skywork/Skywork-Reward-Llama-3.1-8B-v0.2
      revision: main
      source: HF
    max_num_tokens: 131072
    num_builder_gpus: 1
    quantization_type: fp8
  runtime:
    webserver_default_route: /predict
