description: Take in audio and text as input, generating text as usual
base_image:
  image: vllm/vllm-openai:v0.10.0
model_metadata:
  repo_id: mistralai/Voxtral-Small-24B-2507
  avatar_url: https://cdn-avatars.huggingface.co/v1/production/uploads/634c17653d11eaedd88b314d/9OgyfKstSZtbmsmuG8MbU.png
  example_model_input:
    {
      "model": "voxtral-small",
      "messages":
        [
          {
            "role": "user",
            "content":
              [
                {
                  "type": "text",
                  "text": "What is the name of the famous bicycle race in France?",
                },
              ],
          },
        ],
    }
  tags:
    - openai-compatible
docker_server:
  start_command: sh -c "HF_TOKEN=$(cat /secrets/hf_access_token) vllm serve mistralai/Voxtral-Small-24B-2507 --tokenizer_mode mistral --config_format mistral --load_format mistral --port 8000 --served-model-name voxtral-small"
  readiness_endpoint: /health
  liveness_endpoint: /health
  predict_endpoint: /v1/chat/completions
  server_port: 8000
resources:
  accelerator: H100
  use_gpu: true
runtime:
  predict_concurrency: 16
model_name: Voxtral Small 24B 2507
secrets:
  hf_access_token: null
requirements:
  - vllm[audio]==0.10.0
