description: "Chatterbox TTS for text-to-speech"
model_metadata:
  repo_id: "resemble-ai/chatterbox"
  example_model_input: {"text": "Hello, how are you today?"}
model_name: Chatterbox TTS
base_image:
  image: jojobaseten/truss-numpy-1.26.0-gpu:0.4
  python_executable_path: /usr/bin/python3
python_version: py312
requirements:
  - chatterbox-tts==0.1.1
resources:
  accelerator: H100
  cpu: '1'
  memory: 40Gi
  use_gpu: true
secrets:
  hf_access_token: null
