description: Mistral 7B, optimized for chat! Compatible with OpenAI Client
environment_variables: {}
external_package_dirs: []
model_cache:
- allow_patterns:
  - '*.json'
  - '*.safetensors'
  - '*.model'
  repo_id: mistralai/Mistral-7B-Instruct-v0.1
model_metadata:
  avatar_url: https://cdn.baseten.co/production/static/explore/mistral_logo.png
  cover_image_url: https://cdn.baseten.co/production/static/explore/mistral.png
  example_model_input:
    messages:
    - content: What is the mistral wind?
      role: user
  model: mistralai/Mistral-7B-Instruct-v0.1
  repo_id: mistralai/Mistral-7B-Instruct-v0.1
  pretty_name: Mistral 7B Chat
  tags:
  - text-generation
  - openai-compatible
model_name: Mistral 7B Chat
python_version: py311
requirements:
- sentencepiece
- accelerate
- transformers==4.42.3
- torch==2.0.1
- hf_transfer==0.1.4
resources:
  accelerator: A10G
  memory: 25Gi
  use_gpu: true
secrets:
  hf_access_token: "ENTER HF ACCESS TOKEN HERE"
system_packages: []
