model_metadata:
  example_model_input:
    max_tokens: 512
    messages:
      - content: Tell me everything you know about optimized inference.
        role: user
    stream: true
    temperature: 0.5
    chat_template_kwargs:
      enable_thinking: false
  tags:
    - openai-compatible
model_name: qwen3-30b-a3b-instruct-2507-fp8_kv
python_version: py39
resources:
  accelerator: B200
  cpu: "1"
  memory: 10Gi
  use_gpu: true
secrets:
  hf_access_token: null
trt_llm:
  build:
    base_model: decoder
    checkpoint_repository:
      repo: Qwen/Qwen3-30B-A3B-Instruct-2507
      revision: main
      source: HF
    max_seq_len: 40960
    num_builder_gpus: 4
    plugin_configuration:
      use_fp8_context_fmha: true
    quantization_type: fp8_kv
    tensor_parallel_count: 1
  runtime:
    batch_scheduler_policy: max_utilization
    enable_chunked_context: true
