description: "Binoculars AI-generated text detector using Falcon 7B"
environment_variables: {}
external_package_dirs: []
model_cache:
- allow_patterns:
  - '*.bin'
  ignore_patterns:
  - coreml/*
  repo_id: tiiuae/falcon-7b
  use_volume: false
- allow_patterns:
  - '*.bin'
  ignore_patterns:
  - coreml/*
  repo_id: tiiuae/falcon-7b-instruct
  use_volume: false
model_metadata:
  example_model_input: {"text": "The quick brown fox jumps over the lazy dog. This is a sample text to analyze for AI-generated content detection."}
model_name: Binoculars
python_version: py311
requirements:
- git+https://github.com/ahans30/Binoculars.git
resources:
  accelerator: A10G:2
secrets: {}
system_packages: []
