environment_variables: {}
external_package_dirs: []
model_metadata:
  avatar_url: https://cdn.baseten.co/production/static/stability.png
  cover_image_url: https://cdn.baseten.co/production/static/sd.png
  example_model_input:
    prompt: large bed, abstract painting on the wall, fluffy rug on the floor, ambient
      lighting, extremely detailed
  pretty_name: Stable Diffusion ControlNet Depth
  tags:
  - image-generation
model_name: SDXL ControlNet Depth
python_version: py39
requirements:
- accelerate==0.23.0
- transformers==4.33.2
- safetensors==0.3.3
- opencv-python==4.8.0.76
- diffusers==0.21.2
resources:
  accelerator: A10G:2
  cpu: 3500m
  memory: 20Gi
  use_gpu: true
secrets: {}
system_packages:
- ffmpeg
- libsm6
- libxext6
